name: tf-gpu

dependencies:
  - python=3.10.11
  - numpy=1.25.2
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - matplotlib=3.7.2
  - scikit-image=0.21.0
  - opencv=4.8.0
  - pillow=10.0.1
  - ipykernel
  - pip
  - pip:
    - cudatoolkit=11.2
    - cudnn=8.1.0
    - tensorflow==2.10
    - tensorflow-io[tensorflow]
variables:

